### ISSUE TITLE
Bitbucket and globbing broken

### ISSUE THREAD

**Issue by woodfjo** [mrozekma/got#44]
```
bwoodfin@dev:~ $ got <some bitbucket project>/*
Fatal error: Unable to access Bitbucket project repository list without authentication
```
I think this initially did not work, then worked, and now does not work.

**Comment by mrozekma** [comment]
You have to configure the host with a username/password if you want to use globbing, it requires access to the Bitbucket API, which doesn't use your SSH key. I can look into adding oauth support if people actually use that feature though; see #37. Leaving this open until I improve the error message.

**Comment by woodfjo** [comment]
It's not particularly important to me. As long as the error message says what happened and what to do it's fine with me.
